name: React CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm build
      - run: npm test